---

extends: default

ignore: |
  node_modules/

rules:
  line-length:
    ignore: |
      /.github/actions/**/*.yml
      /.github/workflows/*.yml
      /.github/settings.yml
      /docker-compose.yml
      /action.yml
  truthy:
    ignore: |
      /.github/workflows/*.yml
