name: 'github-action-nodejs-template'
description: 'Template for new Github Actions based on Typescript with the Best Practices and Ready to be Released'
author: 'Albert Hernandez'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  name:
    description: 'Name the action will use to say Hello.'
    required: false
    default: 'World'

outputs:
  message:
    description: 'Hello world message'

runs:
  using: 'node20'
  main: 'dist/index.js'
