name: 'github-action-template'
description: 'Template for new Github Actions based on Typescript with the Best Practices and Ready to be Released'
author: alberthernandezdev@gmail.com
runs:
  using: docker
  image: Dockerfile
