---
name: 'Bump version'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@ebc124553a706189378cccb6a34fa836ebff7bc1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: "true"
          output-file: "CHANGELOG.md"
          skip-commit: "true"
          skip-tag: "true"
          skip-on-empty: "true"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
      - name: Create major and minor tags
        if: steps.tag_version.outputs.new_tag
        run: |
          TAG=${{ steps.tag_version.outputs.new_tag }}
          major=${TAG%%.*}
          minor=${TAG%.*}

          echo "Current tag $TAG"
          echo "Major version: $major"
          echo "Minor version: $minor"

          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -fa $major -m "Release v${major}"
          git tag -fa $minor -m "Release v${minor}"

          git push -f origin $major
          git push -f origin $minor
      - name: Release
        if: steps.tag_version.outputs.new_tag
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.changelog.outputs.body }}
